export class InnerCard {
  svg?: string;
  subPlanType?: any;
  id?: any;
  planType?: any;
  amount?: any;
  index?: any;
  planName?: string | undefined;
  planName_?: string;
  planTitle?: string;
  goWifi?: string;
  hasUnli?: boolean;
  callNText?: string;
  contractDuration?: string;
  planAmount?: string;
  payableAmt?: string;
  payableAmtNo?: number;
  simType?: string;
  dataTitle?: string | undefined;
  dataContent?: string | undefined;
  dataFeature?: any;
  hasBadge?: boolean | undefined;
  badgeContent?: string | undefined;
  badgeColor?: any;
  apps?: Array<any> | undefined;
  duration?: string | undefined;
  planFeatures?: any;
  link?: string | undefined;
  backgroundColor?: any;
  primaryColor?: any;
  secondaryColor?: any;
  dataFeatureColor?: any;
  monthlyConsumableAllowance?: any;
  hasUnlimitedAccess?: any;
  name?: any;
  redirectionLink?: any;
  border?: any;
  centerText?: any;
  appDataTitle?: any;
  appData?: any;
  accessDataTitle?: any;
  accessData?: any;
  monthlyConsumableAllowanceTitle?: any;
  roamingTitle?: any;
  roamingDays?: any;
  planBenefits?: any;
}
